---
driver:
  name: dokken
  chef_version: 12.7.2

transport:
        name: dokken

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
          image: centos:7.3.1611

suites:
  - name: motd
    run_list:
      - recipe[motd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
